#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
alias pb='curl -F c=@- https://ptpb.pw/'
MSF_DATABASE_CONFIG='/etc/metasploit/database.yml'
export MSF_DATABASE_CONFIG
