" Vim configuration file 

syntax on
set guifont=Monospace\ Bold\ 12 
colors industry 
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

set showmatch 
"set mouse=a
set tabstop=4
set shiftwidth=4
set smartindent
set autoindent
set cindent
"set mouse=a
