#!/usr/bin/env bash

nscopy() {
  if [[ "$#" -ne 3 ]]; then
    echo "Usage: nscopy machine-name host_source_path dest_path"
  else
    machinectl copy-to $1 $2 $3/${2##*/}
  fi
}

nsretr() {
  if [[ "$#" -ne 3 ]]; then
    echo "Usage: nsretr machine-name machine_source_path host_dest_path"
  else
    machinectl copy-from $1 $2 $3/${2##*/}
  fi
}
