# It's the configuration file for xorg-xinit (startx)

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xrdb -merge ~/.Xresources
# xrandr --output HDMI1 --primary --mode 1920x1080 --dpi 120 --rate 60
# xrandr --output eDP1 --off
# Execute i3wm
# exec i3
XDG_SESSION_TYPE=x11
xhost +local:
exec startxfce4
